version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serverimages
    ports:
      - "4200:4200"
    volumes:
      - ./uploads:/app/uploads:rw
    env_file:
      - .env
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - server-network

networks:
  server-network:
    driver: bridge